const mongoose = require('mongoose');
const Listing = require('./models/Listing');
require('dotenv').config();

const seedListings = async () => {
  await mongoose.connect(process.env.MONGODB_URI);

  // Clear existing listings
  await Listing.deleteMany({});

  const listings = [
    // Special Cons with Manager (Player Packs)
    {
      type: 'coin',
      title: 'José Mourinho + 150🟡',
      description: 'Special Manager Pack with 150 eFootball Coins',
      price: 950,
      amount: 150,
      images: ['/coins/a4i9p0vdi8dd1-removebg-preview.png'],
      playerImage: '/assets/morinho.jpg',
      featured: true,
    },
    {
      type: 'coin',
      title: 'Van Nistelrooy + 100🟡',
      description: 'Special National Team Pack with 100 eFootball Coins',
      price: 600,
      amount: 100,
      images: ['/coins/d9af6ddb1dcd78d12657af728a08421f-removebg-preview.png'],
      playerImage: '/assets/van nistrooy.png',
      featured: true,
    },
    {
      type: 'coin',
      title: 'Mikaël Silverstre + 50🟡',
      description: 'Special National Team Pack with 50 eFootball Coins',
      price: 300,
      amount: 50,
      images: ['/coins/1e933f35ec6ededd0a0ac64294e991ee-removebg-preview.png'],
      playerImage: '/assets/Mikaël Silverstre.png',
      featured: true,
    },
    {
      type: 'coin',
      title: 'David Alaba + 100🟡',
      description: 'Special National Team Pack with 100 eFootball Coins',
      price: 600,
      amount: 100,
      images: ['/coins/d9af6ddb1dcd78d12657af728a08421f-removebg-preview.png'],
      playerImage: '/assets/david alaba.jpg',
      featured: true,
    },
    {
      type: 'coin',
      title: 'Darwin Nunez + 50🟡',
      description: 'Special National Team Pack with 50 eFootball Coins',
      price: 300,
      amount: 50,
      images: ['/coins/1e933f35ec6ededd0a0ac64294e991ee-removebg-preview.png'],
      playerImage: '/assets/darwin nunez.jpg',
      featured: true,
    },
    // Special Manager/National Team Packs
    {
      type: 'coin',
      title: 'France + 50 Coins',
      description: 'France National Team Pack with 50 eFootball Coins',
      price: 299,
      amount: 50,
      images: ['/coins/a4i9p0vdi8dd1-removebg-preview.png'],
    },
    {
      type: 'coin',
      title: 'Netherlands + 100 Coins',
      description: 'Netherlands National Team Pack with 100 eFootball Coins',
      price: 570,
      amount: 100,
      images: ['/coins/d9af6ddb1dcd78d12657af728a08421f-removebg-preview.png'],
    },
    // Coin packages
    {
      type: 'coin',
      title: '130 Coins',
      description: '130 eFootball Coins',
      price: 299,
      amount: 130,
      images: ['/coins/1e933f35ec6ededd0a0ac64294e991ee-removebg-preview.png'],
      featured: true,
    },
    {
      type: 'coin',
      title: '300 Coins',
      description: '300 eFootball Coins',
      price: 589,
      amount: 300,
      images: ['/coins/a4i9p0vdi8dd1-removebg-preview.png'],
      featured: true,
    },
    {
      type: 'coin',
      title: '550 Coins',
      description: '550 eFootball Coins',
      price: 899,
      amount: 550,
      images: ['/coins/1e933f35ec6ededd0a0ac64294e991ee-removebg-preview.png'],
    },
    {
      type: 'coin',
      title: '750 Coins',
      description: '750 eFootball Coins',
      price: 1299,
      amount: 750,
      images: ['/coins/1e933f35ec6ededd0a0ac64294e991ee-removebg-preview.png'],
      featured: true,
    },
    {
      type: 'coin',
      title: '1040 Coins',
      description: '1040 eFootball Coins',
      price: 1650,
      amount: 1040,
      images: ['/coins/a4i9p0vdi8dd1-removebg-preview.png'],
    },
    {
      type: 'coin',
      title: '2130 Coins',
      description: '2130 eFootball Coins',
      price: 3200,
      amount: 2130,
      images: ['/coins/d9af6ddb1dcd78d12657af728a08421f-removebg-preview.png'],
    },
    {
      type: 'coin',
      title: '3250 Coins',
      description: '3250 eFootball Coins',
      price: 5200,
      amount: 3250,
      images: ['/coins/1e933f35ec6ededd0a0ac64294e991ee-removebg-preview.png'],
    },
    {
      type: 'coin',
      title: '5700 Coins',
      description: '5700 eFootball Coins',
      price: 8000,
      amount: 5700,
      images: ['/coins/a4i9p0vdi8dd1-removebg-preview.png'],
    },
    {
      type: 'coin',
      title: '12800 Coins',
      description: '12800 eFootball Coins',
      price: 17000,
      amount: 12800,
      images: ['/coins/d9af6ddb1dcd78d12657af728a08421f-removebg-preview.png'],
      featured: true,
    },
    // Discounted packages
    {
      type: 'coin',
      title: '260 Coins (Discount)',
      description: '260 eFootball Coins - Special Discount',
      price: 350,
      amount: 260,
      images: ['/coins/discount.png'],
      discount: true,
      discountPercentage: 25,
      discountDays: 27,
      discountEndDate: new Date(Date.now() + 27 * 24 * 60 * 60 * 1000),
      featured: true,
    },
    {
      type: 'coin',
      title: '840 Coins (Discount)',
      description: '840 eFootball Coins - Special Discount',
      price: 950,
      amount: 840,
      images: ['/coins/discount.png'],
      discount: true,
      discountPercentage: 20,
      discountDays: 27,
      discountEndDate: new Date(Date.now() + 27 * 24 * 60 * 60 * 1000),
    },
    {
      type: 'coin',
      title: '1100 Coins (Discount)',
      description: '1100 eFootball Coins - Special Discount',
      price: 1300,
      amount: 1100,
      images: ['/coins/discount.png'],
      discount: true,
      discountPercentage: 15,
      discountDays: 27,
      discountEndDate: new Date(Date.now() + 27 * 24 * 60 * 60 * 1000),
    },
    {
      type: 'coin',
      title: '2730 Coins (Discount)',
      description: '2730 eFootball Coins - Special Discount',
      price: 3200,
      amount: 2730,
      images: ['/coins/discount.png'],
      discount: true,
      discountPercentage: 10,
      discountDays: 27,
      discountEndDate: new Date(Date.now() + 27 * 24 * 60 * 60 * 1000),
    },
    // Japan Region
    {
      type: 'coin',
      title: 'Japan 840 Coins',
      description: '840 eFootball Coins - Japan Region',
      price: 950,
      amount: 840,
      images: ['/coins/a4i9p0vdi8dd1-removebg-preview.png'],
      region: 'japan',
      regionImage: '/assets/Flag_of_Japan.svg.png',
    },
    {
      type: 'coin',
      title: 'Japan 260 Coins',
      description: '260 eFootball Coins - Japan Region',
      price: 350,
      amount: 260,
      images: ['/coins/a4i9p0vdi8dd1-removebg-preview.png'],
      region: 'japan',
      regionImage: '/assets/Flag_of_Japan.svg.png',
    },
    {
      type: 'coin',
      title: 'Japan 2700 Coins',
      description: '2700 eFootball Coins - Japan Region Special',
      price: 2900,
      amount: 2700,
      images: ['/coins/a4i9p0vdi8dd1-removebg-preview.png'],
      region: 'japan',
      regionImage: '/assets/Flag_of_Japan.svg.png',
    },
    // Accounts
    {
      type: 'account',
      title: 'Pro Account Lv.50',
      description: 'High-level account with legendary players',
      price: 49.99,
      rating: 94,
      level: 50,
      coins: 2000000,
      players: 45,
      images: ['/teams/2abc9e5b3b48009af50a016530aa6af6.jpg'],
      discount: true,
    },
    {
      type: 'account',
      title: 'Starter Account Lv.20',
      description: 'Perfect for beginners with good foundation',
      price: 19.99,
      rating: 82,
      level: 20,
      coins: 500000,
      players: 25,
      images: ['/teams/352be9320c1d8682ce6b0da5aeb51aaa.jpg'],
    },
    {
      type: 'account',
      title: 'Elite Account Lv.80',
      description: 'Top-tier account with full squad',
      price: 99.99,
      rating: 97,
      level: 80,
      coins: 5000000,
      players: 60,
      images: ['/teams/3d0fac9139511c599579d12daeffdf85.jpg'],
      discount: true,
    },
    {
      type: 'account',
      title: 'Mid-tier Account Lv.35',
      description: 'Balanced account for competitive play',
      price: 34.99,
      rating: 88,
      level: 35,
      coins: 1000000,
      players: 35,
      images: ['/teams/4d16b11b664be199dc41acc9ee2d9c79.jpg'],
    },
    // Teams
    {
      type: 'team',
      title: 'Team One',
      description: 'Complete team one',
      price: 3600,
      formation: '4-3-3',
      rating: 90,
      players: ['Player1', 'Player2', 'Player3', 'Player4'],
      images: ['/teams/2abc9e5b3b48009af50a016530aa6af6.jpg'],
      discount: true,
    },
    {
      type: 'team',
      title: 'Team 2',
      description: 'Complete team 2',
      price: 4800,
      formation: '4-3-3',
      rating: 91,
      players: ['Player5', 'Player6', 'Player7', 'Player8'],
      images: ['/teams/352be9320c1d8682ce6b0da5aeb51aaa.jpg'],
    },
    {
      type: 'team',
      title: 'Team 3',
      description: 'Complete team 3',
      price: 9888,
      formation: '4-2-3-1',
      rating: 92,
      players: ['Player9', 'Player10', 'Player11', 'Player12'],
      images: ['/teams/3d0fac9139511c599579d12daeffdf85.jpg'],
      discount: true,
    },
    {
      type: 'team',
      title: 'Team 4',
      description: 'Complete team 4',
      price: 7328,
      formation: '4-3-3',
      rating: 93,
      players: ['Player13', 'Player14', 'Player15', 'Player16'],
      images: ['/teams/4d16b11b664be199dc41acc9ee2d9c79.jpg'],
    },
    {
      type: 'team',
      title: 'Team 5',
      description: 'Complete team 5',
      price: 3233,
      formation: '4-2-3-1',
      rating: 94,
      players: ['Player17', 'Player18', 'Player19', 'Player20'],
      images: ['/teams/83b2288ce46adf26ccded8a2677ce6d1.jpg'],
    },
    {
      type: 'team',
      title: 'Team 6',
      description: 'Complete team 6',
      price: 4777,
      formation: '4-3-3',
      rating: 95,
      players: ['Player21', 'Player22', 'Player23', 'Player24'],
      images: ['/teams/e31b1b057ca3b49857a23114ac0e5e71.jpg'],
      discount: true,
    },
  ];

  await Listing.insertMany(listings);
  console.log('Listings seeded');
  process.exit();
};

seedListings();
